### ISSUE TITLE
app.js does not exist

### ISSUE THREAD

**Issue by superwavepool** [ricreis394/plex-library-html#2]
<script type="module" src="/dist/app.js"></script> in index.html

/dist/app.js does not exist.

**Comment by plckr** [comment]
Sorry forgot to mention you have to compile
Run `npm run build` to compile
Will update readme later

**Comment by superwavepool** [comment]
please do update the readme with included required packages etc. I like what you have created but I cannot get it to work even with `npm run build` with no errors etc.

**Comment by plckr** [comment]
> please do update the readme with included required packages etc. I like what you have created but I cannot get it to work even with `npm run build` with no errors etc.

I've been away from the computer. I'll try until tomorrow to update the repo
