### ISSUE TITLE
issue with language?

### ISSUE THREAD

**Issue by superwavepool** [ricreis394/plex-library-html#3]
app.js:1218 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'countryCode')
    at app.js:1218
    at async Promise.all (/index 0)

get this error when running in a browser. Have spent a few months trying to get this to work - would really appreciate either a more detailed readme or some work on the code.

No issues compiling etc, just end up with a spinning wheel.

**Comment by plckr** [comment]
Will check it asap
Which language is in your plex?

**Comment by plckr** [comment]
Seems like the app can't connect to Plex server
Can you try going to this url `/api/server` ? And check if data is returning
